### ISSUE TITLE
Fill missing sample to display Java examples in MeiliSearch Documentation

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#244]
**Description**
The Java Code Samples for MeiliSearch documentation are almost complete.
There are only 3 samples missing:
```yaml
getting_started_add_documents_md: |-
getting_started_search_md: |-
add_movies_json_1: |-
```

For instructions and more information see: #20.
