### ISSUE TITLE
Add methods for the setting the Sortable Attribute

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#491]
Add method related to settings `sortableAttributes`:
- [x] `getSortableAttributesSettings`
- [x] `updateSortableAttributesSettings`
- [x] `resetSortableAttributesSettings`
- [x] Add tests
- [x] Add sample in the code-sample file

**EDIT:**
The code sample should be modified in the `.code-samples.meilisearch.yaml` like:
line 619:
```yaml
sorting_guide_update_sortable_attributes_1: |-
  client.index("books").updateSortableAttributesSettings(new String[] {"price", "author"});
```
line 663:
```yaml
geosearch_guide_sort_settings_1: |-
  client.index("restaurants").updateSortableAttributesSettings(new String[] {"_geo"});
```
line 641:
```yaml
get_sortable_attributes_1: |-
  client.index("books").getSortableAttributesSettings();
update_sortable_attributes_1: |-
  client.index("books").updateSortableAttributesSettings(new String[] {"price", "author"});
reset_sortable_attributes_1: |-
  client.index("books").resetSortableAttributesSettings();
```
